services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file: ./.env
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: local
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
